// Package customersapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package customersapi

import (
	"time"
)

const (
	Sigv4Scopes = "sigv4.Scopes"
)

// Customer response.
type Customer struct {
	// The timestamp the customer was created
	CreatedAt time.Time `json:"created_at"`

	// A description of the customer, with some background.
	Description *string `json:"description,omitempty"`

	// Customer identifier.
	Id string `json:"id"`

	// Labels assigned to an entity.
	Labels []string `json:"labels"`

	// The name of the customer.
	Name string `json:"name"`

	// The timestamp the customer was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// Customer page response.
type CustomersPage struct {
	Customers []Customer `json:"customers"`
	NextToken *string    `json:"nextToken,omitempty"`
}

// New Customer.
type NewCustomer struct {
	// A description of the customer, with some background.
	Description *string `json:"description,omitempty"`

	// Labels assigned to an entity.
	Labels []string `json:"labels"`

	// The name of the customer, this must be unique.
	Name string `json:"name"`
}

// UpdatedCustomer defines model for UpdatedCustomer.
type UpdatedCustomer struct {
	// A description of the customer, with some background.
	Description *string `json:"description,omitempty"`

	// Labels assigned to an entity.
	Labels []string `json:"labels"`

	// The name of the customer, this must be unique.
	Name    string `json:"name"`
	Version int64  `json:"version"`
}

// CustomersParams defines parameters for Customers.
type CustomersParams struct {
	NextToken *string `form:"nextToken,omitempty" json:"nextToken,omitempty"`
	MaxItems  *int    `form:"maxItems,omitempty" json:"maxItems,omitempty"`
}

// NewCustomerJSONBody defines parameters for NewCustomer.
type NewCustomerJSONBody = NewCustomer

// UpdateCustomerJSONBody defines parameters for UpdateCustomer.
type UpdateCustomerJSONBody = UpdatedCustomer

// NewCustomerJSONRequestBody defines body for NewCustomer for application/json ContentType.
type NewCustomerJSONRequestBody = NewCustomerJSONBody

// UpdateCustomerJSONRequestBody defines body for UpdateCustomer for application/json ContentType.
type UpdateCustomerJSONRequestBody = UpdateCustomerJSONBody
