name: Go
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: CI Tasks
        run: make ci
      # Run Spectral
      - uses: stoplightio/spectral-action@v0.5.5
        with:
          file_glob: 'openapi/*.yaml'